import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Sidebar from '@/components/sidebar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PICTURE GALLLERY',
  description: 'Generated by Abdul-1302',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <Navbar/>
        <div className='flex'>
          <div className='w-1/4 '>
            <Sidebar/>
          </div>
          <div className='w-full'>{children}</div>
        </div>
        </body>
    </html>
  )
}
